<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->baseUrl();?>/static/framework/bootstrap/css/bootstrap.min.css"/>
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->baseUrl();?>/static/styles/admin/controlpanel.css"/>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/js/jquery.min.js"></script>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/framework/bootstrap/js/bootstrap.min.js"></script>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/js/admin/jquery.dialog.js"></script>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/js/admin/controlpanel.js"></script>
</head>
<body>
<div class="row tabs-wrap">
    <div class="col-xs-10">
        <ul class="nav nav-tabs">
            <li class="active"><a href="<?php echo $this->url(array("module" => "admin", "controller" => "controlpanel", "action" => "navigat"), null, true);?>">管理网站导航</a></li>
        </ul>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" role="form" id="controlpanel-navigat-form">
            <table class="table table-bordered table-striped" id="navigat-inputarea">
                <thead>
                    <th>导航名称</th>
                    <th>链接地址</th>
                    <th>排列顺序</th>
                    <th>操作信息</th>
                    <th>&nbsp;</th>
                </thead>
                <tbody>
                    <?php if (count($this->navigatList) == 0) { ?>
                    <tr>
                        <td><input type="text" name="naviname[]" class="form-control input-sm"/></td>
                        <td><input type="text" name="location[]" class="form-control input-sm"/></td>
                        <td><input type="text" name="sequence[]" class="form-control input-sm"/></td>
                        <td><a id="navigat-inputarea-add" href="javascript:;" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-plus"></i> 增加导航</a></td>
                        <td>&nbsp;</td>
                    </tr>
                    <?php } else { ?>
                    <?php foreach ($this->navigatList as $key => $val) { ?>
                    <tr>
                        <td><input type="text" name="naviname[]" class="form-control input-sm"
                                   value="<?php echo $val->getNaviName();?>"/></td>
                        <td><input type="text" name="location[]" class="form-control input-sm"
                                   value="<?php echo $val->getLocation();?>"/></td>
                        <td><input type="text" name="sequence[]" class="form-control input-sm"
                                   value="<?php echo $val->getSequence();?>"/></td>
                        <td><?php echo $val->getCreatedUser();?>&nbsp;<?php echo $val->getCreatedTime();?><br>
                            <span name="ipconvert"><?php echo $val->getCreatedIp();?></span></td>
                        <td class="text-center">
                            <?php if ($key == 0) { ?>
                            <a id="navigat-inputarea-add" href="javascript:;" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-plus"></i> 增加导航</a>
                            <?php } else { ?>
                            <a href="javascript:;" onclick="javascript:$(this).parent().parent().remove()" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-minus"></i> 删除导航</a>
                            <?php }?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php } ?>
                </tbody>
            </table>
            <a class="btn btn-warning" id="controlpanel-navigat-button">修改导航</a>
        </form>
    </div>
</div>
<p class="text-center">
    Powered&nbsp;By&nbsp;<a href="https://github.com/NoteYun/MountainKing" target="_blank">MountainKing</a>&nbsp;2012-<?php echo date("Y");?>&nbsp;&copy;&nbsp;<a href="http://noteyun.com/" target="_blank">NoteYun.COM</a>
</p>
</body>
<script type="text/javascript">
$("#navigat-inputarea-add").click(function () {
    var navigatInputAreaHTML = '<tr>' + 
        '<td><input type="text" name="naviname[]" class="form-control input-sm"/></td>' +
        '<td><input type="text" name="location[]" class="form-control input-sm"/></td>' +
        '<td><input type="text" name="sequence[]" class="form-control input-sm"/></td>' +
        '<td>&nbsp;</td>' + 
        '<td class="text-center"><a class="btn btn-sm btn-danger" href="javascript:;" onclick="javascript:$(this).parent().parent().remove()"><i class="glyphicon glyphicon-minus"></i> 删除导航</a></td>' +
        '</tr>';
    $('#navigat-inputarea').append(jQuery(navigatInputAreaHTML));
    $('#controlpanel-frame', window.top.document).css({"height":$(window.document).height()});
});
$("#controlpanel-navigat-button").click(function () {
    $.ajax({
        data:$("#controlpanel-navigat-form").serialize(),
        type:"post",
        url:"<?php echo $this->url(array("module" => "admin", "controller" => "controlpanel", "action" => "navigat"), null, true);?>",
        success:function (transport) {
            var response = jQuery.parseJSON(transport);
            if (response.flag == false) {
                $.dialog({
                    "argvCallback":function () {
                    },
                    "argvElement":"replaceNavigatDialog",
                    "argvWidth":350,
                    "argvHeight":75,
                    "argvMessage":response.text
                });
                return false;
            } else {
                $.dialog({
                    "argvCallback":function () {
                        window.location.href = '<?php echo $this->url(array("module" => "admin", "controller" => "controlpanel", "action" => "navigat"), null, true);?>';
                    },
                    "argvElement":"replaceNavigatDialog",
                    "argvWidth":350,
                    "argvHeight":75,
                    "argvMessage":"修改成功，您已经成功修改网站导航设置"
                });
                return true;
            }
        }
    });
});
$(function () {
    $('span[name="ipconvert"]').each(function () {
        var converted = controlPanel.tinyipConvert(this.innerHTML);
        this.innerHTML = converted + "&nbsp;&nbsp;" + this.innerHTML;
    });
});
</script>
</html>