<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->baseUrl();?>/static/framework/bootstrap/css/bootstrap.min.css"/>
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->baseUrl();?>/static/styles/admin/controlpanel.css"/>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/js/jquery.min.js"></script>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/framework/bootstrap/js/bootstrap.min.js"></script>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/js/admin/jquery.dialog.js"></script>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/js/admin/controlpanel.js"></script>
</head>
<body>
<div class="row tabs-wrap">
    <div class="col-xs-10">
        <ul class="nav nav-tabs">
            <li class="active"><a href="<?php echo $this->url(array("module" => "admin", "controller" => "controlpanel", "action" => "viewlog"), null, true);?>">查看错误日志</a></li>
        </ul>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <thead>
                <th>日志文件</th>
                <th>文件路径</th>
                <th>文件大小</th>
                <th>最后修改日期</th>
                <th>&nbsp;</th>
            </thead>
            <tbody>
                <?php if (count($this->logList) == 0) { ?>
                <tr>
                    <td colspan="5">未找到符合条件的记录项</td>
                </tr>
                <?php } else { ?>
                <?php foreach ($this->logList as $key => $val) { ?>
                <tr>
                    <td><?php echo $val["name"];?></td>
                    <td><?php echo $val["path"];?></td>
                    <td><?php echo $val["size"];?>&nbsp;KB</td>
                    <td><?php echo $val["time"];?></td>
                    <td class="text-center"><a href="javascript:void(0);" onclick="javascript:viewLog('<?php echo $val["name"];?>');" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-file"></i> 查看日志</a></td>
                </tr>
                <?php }?>
                <?php }?>
            </tbody>
        </table>
    </div>
</div>
</body>
<script type="text/javascript">
function viewLog(logFile) {
    $.ajax({
        data:"logfile=" + logFile,
        type:"post",
        url:"<?php echo $this->url(array("module" => "admin", "controller" => "controlpanel", "action" => "viewlog"), null, true);?>",
        success:function (transport) {
            var response = jQuery.parseJSON(transport);
            if (response.flag == false) {
                $.dialog({
                    "argvCallback":function () {
                    },
                    "argvElement":"viewLogDialog",
                    "argvWidth":350,
                    "argvHeight":75,
                    "argvMessage":response.text
                });
                return false;
            } else {
                $.dialog({
                    "argvCallback":function () {
                    },
                    "argvElement":"viewLogDialog",
                    "argvWidth":900,
                    "argvHeight":400,
                    "argvSubject":"读取成功",
                    "argvMessage":"<div style=\"text-align:left; font-size:12px; font-weight:400;\">" + response.text + "</div>"
                });
                return true;
            }
        }
    });
}
</script>
</html>