<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->baseUrl();?>/static/framework/bootstrap/css/bootstrap.min.css"/>
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->baseUrl();?>/static/styles/admin/controlpanel.css"/>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/js/jquery.min.js"></script>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/framework/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<div class="row tabs-wrap">
    <div class="col-xs-10">
        <ul class="nav nav-tabs">
            <li class="active"><a href="<?php echo $this->url(array("module" => "admin", "controller" => "index", "action" => "admin"), null, true);?>">网站总览</a></li>
        </ul>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><span class="glyphicon glyphicon-cog"></span> 网站配置</div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <thead>
                <th>项目</th>
                <th>配置</th>
            </thead>
            <tbody>
                <tr>
                    <td>网站名称（TITLE）</td>
                    <td><?php echo $this->websiteHtmlTitle;?>&nbsp;<?php if ($this->websiteCloseSign) {?><span class="label label-danger">维护中...</span><?php } else {?><span class="label label-success">运行中...</span><?php }?></td>
                </tr>
                <tr>
                    <td>META关键词</td>
                    <td><?php echo $this->websiteMetaKeywords;?></td>
                </tr>
                <tr>
                    <td>META备注</td>
                    <td><?php echo $this->websiteMetaDescript;?></td>
                </tr>
                <tr>
                    <td>前台访问地址</td>
                    <td><?php if ($this->baseUrl() == "") {echo $_SERVER["HTTP_HOST"];} else {echo $this->baseUrl();}?></td>
                </tr>
                <tr>
                    <td>附件访问前缀</td>
                    <td><?php echo $this->attachmentHostName;?></td>
                </tr>
                <tr>
                    <td>附件存储路径</td>
                    <td><?php echo $this->attachmentRootPath;?></td>
                </tr>
                <tr>
                    <td>访问统计代码</td>
                    <td><?php echo htmlspecialchars($this->websiteVisitAnalytics);?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="panel-heading"><span class="glyphicon glyphicon-bell"></span> 数据统计</div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <td>网站栏目&nbsp;
                        <span class="label label-info">总数：<?php echo $this->categoryNums;?></span>
                    </td>
                    <td>网站内容&nbsp;
                        <span class="label label-info">总数：<?php echo $this->contentsNums;?></span>
                        <span class="label label-warning">未审核：<?php echo $this->unpublicContentsNums;?></span>
                    </td>
                    <td>内容评论&nbsp;
                        <span class="label label-info">总数：<?php echo $this->commentNums;?></span>
                        <span class="label label-warning">未审核：<?php echo $this->unpublicCommentNums;?></span>
                    </td>
                    <td>附件上传&nbsp;
                        <span class="label label-info">总数：<?php echo $this->attachmentNums;?></span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<p class="text-center">
    Powered&nbsp;By&nbsp;<a href="https://github.com/NoteYun/MountainKing" target="_blank">MountainKing</a>&nbsp;2012-<?php echo date("Y");?>&nbsp;&copy;&nbsp;<a href="http://noteyun.com/" target="_blank">NoteYun.COM</a>
</p>
</body>
</html>