<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Runtime Exception</title>
</head>
<style type="text/css">
    *, body, html {
        font-family: "Times New Roman", Tahoma, SimSun, Arial;
        font-size: 12px;
    }
</style>
<body>
<?php if (isset($this->exception)): ?>
<p style="color:#ff0000; font-weight:600; font-size:14px;">Runtime Exception</p>
<p style="border-bottom:1px solid #cccccc; margin-bottom:10px; height:35px; line-height:35px;">
    <b>Description：</b><?php echo $this->exception->getMessage(); ?></p>
<p style="color:#000000; font-weight:600; font-size:12px;">Exception Stack Trace:</p>
<p>
<pre style="padding:10px 5px; background:#fffff0;"><?php echo $this->exception->getTraceAsString();?></pre>
</p>
<p style="color:#000000; font-weight:600; font-size:12px;">Request Parameters:</p>
<p>
<pre
    style="padding:10px 5px; background:#fffff0;"><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
</p>
    <?php endif ?>
</body>
</html>