<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=7"/>
    <title><?php echo $this->configWebsiteHtmlTitle;?> - <?php echo $this->maintenance;?></title>
    <link href="<?php echo $this->baseUrl();?>/static/favicon.ico" type="image/x-icon" rel="shortcut icon"/>
    <link href="<?php echo $this->baseUrl();?>/static/favicon.ico" type="image/x-icon" rel="bookmark"/>
</head>
<body>
<div>
    <p align="center">
        <img src="<?php echo $this->baseUrl();?>/static/images/maintenance.gif"/>
    </p>
</div>
</body>
</html>