<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->baseUrl();?>/static/framework/bootstrap/css/bootstrap.min.css"/>
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->baseUrl();?>/static/styles/admin/controlpanel.css"/>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/js/jquery.min.js"></script>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/framework/bootstrap/js/bootstrap.min.js"></script>
    <script charset="utf-8" type="text/javascript" src="<?php echo $this->baseUrl();?>/static/js/admin/jquery.dialog.js"></script>
</head>
<body>
<div class="row tabs-wrap">
    <div class="col-xs-10">
        <ul class="nav nav-tabs">
            <li class="active"><a href="<?php echo $this->url(array("module" => "admin", "controller" => "administrator", "action" => "password"), null, true);?>">修改密码</a></li>
        </ul>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" role="form" id="administrator-password-form">
        <div class="form-group">
            <label for="old_password" class="control-label col-md-3">
                <p class="text-left">当前密码：<br/><span class="help-block">请输入您当前使用的密码以便进行鉴权</span></p>
            </label>
            <div class="control-wrap col-md-3">
                <input type="password" class="form-control input-sm" id="old_password" name="old_password" maxlength="20"/>
            </div>
        </div>
        <div class="form-group">
            <label for="new_password" class="control-label col-md-3">
                <p class="text-left">设置密码：<br/><span class="help-block">请输入新密码，长度为5-20个英文字符</span></p>
            </label>
            <div class="control-wrap col-md-3">
                <input type="password" class="form-control input-sm" id="new_password" name="new_password" maxlength="20"/>
            </div>
        </div>
        <div class="form-group">
            <label for="cfm_password" class="control-label col-md-3">
                <p class="text-left">设置密码：<br/><span class="help-block">再次输入新密码，两次密码输入需一致</span></p>
            </label>
            <div class="control-wrap col-md-3">
                <input type="password" class="form-control input-sm" id="cfm_password" name="cfm_password" maxlength="20"/>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-3"></div>
            <div class="control-wrap col-md-3">
                <a class="btn btn-warning" id="administrator-password-button">修改密码</a>
            </div>
        </div>
        </form>
    </div>
</div>
<p class="text-center">
    Powered&nbsp;By&nbsp;<a href="https://github.com/NoteYun/MountainKing" target="_blank">MountainKing</a>&nbsp;2012-<?php echo date("Y");?>&nbsp;&copy;&nbsp;<a href="http://noteyun.com/" target="_blank">NoteYun.COM</a>
</p>
</body>
<script type="text/javascript">
$("#old_password").focus(function() {
    $("#old_password").popover("destroy");
    $("#new_password").popover("destroy");
    $("#cfm_password").popover("destroy");
});
$("#new_password").focus(function() {
    $("#old_password").popover("destroy");
    $("#new_password").popover("destroy");
    $("#cfm_password").popover("destroy");
});
$("#cfm_password").focus(function() {
    $("#old_password").popover("destroy");
    $("#new_password").popover("destroy");
    $("#cfm_password").popover("destroy");
});

$("#administrator-password-button").click(function () {
    var oldPassword = $.trim($("#old_password").val());
    var newPassword = $.trim($("#new_password").val());
    var cfmPassword = $.trim($("#cfm_password").val());
    
    if (oldPassword.length < 5 || oldPassword.length > 20) {
        $("#old_password").popover({
            placement:"right",
            container:"body",
            content:"密码修改失败，您输入的当前密码为空或格式错误"
        });
        $("#old_password").popover("show");
        return false;
    }
    
    if (newPassword.length < 5 || newPassword.length > 20) {
        $("#new_password").popover({
            placement:"right",
            container:"body",
            content:"密码修改失败，您输入的新密码为空或格式错误"
        });
        $("#new_password").popover("show");
        return false;
    }

    if (cfmPassword.length < 5 || cfmPassword.length > 20) {
        $("#cfm_password").popover({
            placement:"right",
            container:"body",
            content:"密码修改失败，您输入的确认密码为空或格式错误"
        });
        $("#cfm_password").popover("show");
        return false;
    }

    if (cfmPassword != newPassword) {
        $("#cfm_password").popover({
            placement:"right",
            container:"body",
            content:"密码修改失败，您两次输入的密码不一致"
        });
        $("#cfm_password").popover("show");
        return false;
    }

    $.ajax({
        data:$("#administrator-password-form").serialize(),
        type:"post",
        url:"<?php echo $this->url(array("module" => "admin", "controller" => "administrator", "action" => "password"), null, true);?>",
        success:function (transport) {
            var response = jQuery.parseJSON(transport);
            if (response.flag == false) {
                $.dialog({
                    "argvCallback":function () {},
                    "argvElement":"editPasswordDialog",
                    "argvZindex":99999,
                    "argvWidth":350,
                    "argvHeight":75,
                    "argvMessage":response.text
                });
                return false;
            } else {
                $.dialog({
                    "argvCallback":function () {
                        $("#old_password").val("");
                        $("#new_password").val("");
                        $("#cfm_password").val("");
                    },
                    "argvElement":"editPasswordDialog",
                    "argvZindex":99999,
                    "argvWidth":350,
                    "argvHeight":75,
                    "argvMessage":"密码修改成功，下次登录请使用新设置的密码"
                });
                return true;
            }
        }
    });
});
</script>
</html>
